src/app.py
import os

from flask import Flask
from flaskext.markdown import Markdown

from blueprints.index_blueprint import index_blueprint


if __name__ == '__main__':

    app = Flask(__name__)
    app.register_blueprint(index_blueprint)
    Markdown(app)

    app.jinja_env.auto_reload = True
    app.config['TEMPLATES_AUTO_RELOAD'] = True
    app.run(debug=True, host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))

src/blueprints/index_blueprint.py
from flask import Blueprint, render_template

import os
import json

index_blueprint = Blueprint('index_blueprint', __name__)
entries_dir_path = 'entries'

@index_blueprint.route('/<entry_name>', methods=['GET'])
def entry(entry_name):

    entry_dir = os.path.join(entries_dir_path, entry_name)

    with open(os.path.join(entry_dir, 'text.txt'), 'r') as f:
        text = f.read()

    with open(os.path.join(entry_dir, 'metadata.json'), 'r') as f:
        metadata = json.load(f)
        timestamp = metadata['timestamp']

    entry = {'text': text, 'timestamp': timestamp, 'path': entry_dir}

    return render_template('entry.html', entry=entry)


@index_blueprint.route('/', methods=['GET'])
def index():
    entries = []
    
    for entry_name in os.listdir(entries_dir_path):
        
        entry_dir = os.path.join(entries_dir_path, entry_name)
        
        with open(os.path.join(entry_dir, 'text.txt'), 'r') as f:
            text = f.read()

        with open(os.path.join(entry_dir, 'metadata.json'), 'r') as f:
            metadata = json.load(f)
            timestamp = metadata['timestamp']

        entries.append({'text': text, 'timestamp': timestamp, 'name': entry_name})

    return render_template('index.html', entries=entries)
    

src/templates/base.html
<!DOCTYPE html>

<html>

<head>
    <h1>web log</h1>
</head>

<hr>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

src/templates/entry.html
{% extends "base.html" %}

{% block content %}

{{ entry['timestamp'] }}
<br>
<pre>
{{ entry['text'] | markdown }}
</pre>

<style>
pre {
    font-family: "Times New Roman", Times, serif;
}
</style>

{% endblock %}

src/templates/index.html
{% extends "base.html" %}

{% block content %}

{% for entry in entries %}
    {{ entry['timestamp'] }}
    <a href="{{ url_for('index_blueprint.entry', entry_name=entry['name']) }}">[Link]</a>
    <br>
    <pre>
    {{ entry['text'] | markdown }}
    </pre>
    <hr>
{% endfor %}

<style>
    pre {
        font-family: "Times New Roman", Times, serif;
    }
</style>

{% endblock %}